dist: trusty
language: scala
jdk: openjdk8
scala:
    - 2.11.11
    - 2.12.3

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
